In [17]:
import numpy as np
arr=np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [18]:
arr=np.random.random((3,3))
arr


array([[0.52269683, 0.93735722, 0.28780825],
       [0.32230325, 0.96478467, 0.28670782],
       [0.15507008, 0.19805697, 0.69685316]])

In [19]:
arr1=np.array([[1,2,3],[4,5,6]])
print("shape:",arr1.shape)
print("Size:",arr1.size)
print("data_type:",arr.dtype)

shape: (2, 3)
Size: 6
data_type: float64


In [21]:
arr=np.array([10,20,30])
print(arr+5)

[15 25 35]


In [73]:
arr_21=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_22=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_21*arr_22)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [30]:
arr = np.arange(1, 26).reshape(5, 5)
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [31]:
first_row = arr[0]
print(first_row)

[1 2 3 4 5]


In [32]:
last_column = arr[:, -1]
print(last_column)

[ 5 10 15 20 25]


In [38]:
subarray = arr[:3, :2]
print(subarray)

[[ 1  2]
 [ 6  7]
 [11 12]]


In [45]:
arr = np.random.randint(1, 101, 10)
print(arr)
print("Maximum",arr.max())
print("Minimum",arr.min())
print("Mean",arr.mean())
print("Standard Deviation",arr.std())

[58 18 71 22  9 45 90  9 81 66]
Maximum 90
Minimum 9
Mean 46.9
Standard Deviation 29.01878701806814


In [54]:
arr=np.arange(1,13)
print(arr.reshape(3,4))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [74]:
ones=np.ones((3,3))
print(ones+(1,2,3))

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [72]:
arr=np.random.randint(1,51,10)
divisible_by_5 = arr[arr % 5 == 0]
print("Array:", arr)
print("Elements divisible by 5:", divisible_by_5)


Array: [16 28 29 50 33 10 19 29 13 28]
Elements divisible by 5: [50 10]


In [75]:

arr_21=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_22=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.dot(arr_21,arr_22))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [82]:
arr = np.arange(1, 17).reshape(4, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [83]:
diagonal_elements = np.diagonal(arr)
print(diagonal_elements)

[ 1  6 11 16]
